#!/bin/bash

umask 002

if [[ -f /opt/view/rlec/S3 ]]; then
	YAML=s3-redis-modules.yaml
else
	YAML=redis-modules.yaml
fi

[[ -f /opt/view/rlec/NOMODULES ]] && { echo "Skipping modules installation." ; exit 0; }
[[ ! -f /opt/view/rlec/$YAML ]] && { echo "No modules specified." ; exit 0; }

# rm -f /opt/redislabs/lib/modules/*

OP=""
echo "Installing modules..."
if [[ $BB == 1 ]]; then
	OP="/opt/redislabs/bin/python -O -m pudb"
fi
$OP /opt/view/arlecchino/rlec/internal/install-modules.py --yaml /opt/view/rlec/$YAML --modinfo /opt/view/rlec/modules.json
